services:
  bgr-sign-api:
    build: .
#    image: bgr-sign-api:latest
    container_name: bgr-sign-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bgr_sign_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./configuration:/app/configuration
    restart: always
    networks:
      - springboot-network

networks:
  springboot-network:
    external: true
    name: springboot-network
