services:
  postgres:
    image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bgr_sign_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]
    networks:
      - springboot-network
#    networks:
#      springboot-network:
#        aliases:
#          - postgres
networks:
  springboot-network:
    external: true
    name: springboot-network

volumes:
  postgres_data:
