services:
  bgr-sign-api:
    build: .
    container_name: bgr-sign-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bgr_sign_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    #    volumes:
    #      - ./configuration:/app/configuration
    restart: unless-stopped
    networks:
      - springboot-network


networks:
  springboot-network:
    external: true
    name: springboot-network
