services:
  bgr-sign-api:
    #    build: .
    image: registry.bgrfacile.com/bgr-sign-api:latest
    container_name: bgr-sign-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bgr_sign_db
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    volumes:
#      - ./configuration:/app/configuration
    restart: always
    networks:
      #      - springboot-network
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.bgr-sign-api.rule=Host(`${DOMAINE_NAME:-api.bgrsign.bgrfacile.com}`)
      - traefik.http.routers.bgr-sign-api.entrypoints=websecure
      - traefik.http.routers.bgr-sign-api.tls.certresolver=le
      - traefik.http.services.bgr-sign-api.loadbalancer.server.port=8080

networks:
  traefik-network:
    external: true
    name: traefik-network
#  springboot-network:
#    external: true
#    name: springboot-network
