spring:
  config:
    activate:
      on-profile: prod
    import: "file:configuration/prod.properties"
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-db-server}:5432/bgr_sign_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    enabled: false
    validate-on-migrate: true

logging:
  level:
    root: warn
    org.flywaydb: info

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 604800000

debug: false