spring:
  application:
    name: bgr-sign-api
  jmx:
    enabled: false
  config:
    activate:
      on-profile: dev
    import: "optional:file:configuration/dev.properties"
  datasource:
    url: jdbc:postgresql://localhost:5432/bgr_sign_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#    hikari:
#      data-source-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration
    enabled: false
    validate-on-migrate: true

logging:
  level:
    root: debug
    org.flywaydb: info

app:
  jwtSecret: ${JWT_SECRET:L6+d9T3viXB/RHXjBFz6W/QsHmawRIcEhLbpueT3Ih+sY5jHuzlYKILljLAWB6KPmPWiohLXM1Lcy/LYMFwhgw==}
  jwtExpirationInMs: 604800000

debug: true

server:
  port: 8080