spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bgr_sign_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #  ddl-auto: none
    # (Optionnel) Affiche les requêtes SQL dans la console :
    # show-sql: true
    # format-sql: true

  flyway:
    locations: classpath:db/migration
    enabled: false

  application:
    name: bgr-sign-api

logging:
  level:
    org.flywaydb: info

app:
  jwtSecret: "X7Ad9qh37bS1zP1zP1T09yZ3k8KYLS5fSE0tPNQ1It5Fz18JPycdkZxzOqPQZ1zH"
  jwtExpirationInMs: 604800000

server:
  port: 8081

debug: true
